name: Close Issues Based on Labels

on:
  issues:
    types: [labeled]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue as not planned if labeled with 'âŒ æ‹’ç»'
        if: github.event.label.name == 'âŒ æ‹’ç»'
        uses: peter-evans/close-issue@v3
        with:
          state: closed
          reason: 'not_planned'
        env:
          GITHUB_TOKEN: ${{ secrets.SHEEP }}

      - name: Close issue as completed if labeled with 'ğŸ‘Œ å®Œæˆ'
        if: github.event.label.name == 'ğŸ‘Œ å®Œæˆ'
        uses: peter-evans/close-issue@v3
        with:
          state: closed
          reason: 'completed'
        env:
          GITHUB_TOKEN: ${{ secrets.SHEEP }}
