name: Issue Management

on:
  issues:
    types:
      - labeled
      - closed

jobs:
  manage_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Set up authentication
        run: |
          echo "GITHUB_TOKEN=${{ secrets.SHEEP }}" >> $GITHUB_ENV

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Handle labeled issues
        if: github.event.action == 'labeled'
        run: |
          if [[ "${{ github.event.label.name }}" == "âŒ æ‹’ç»" || "${{ github.event.label.name }}" == "ğŸ˜‚ ç§»äº¤ä¸Šæ¸¸" ]]; then
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.SHEEP }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
              -d '{"state": "closed", "state_reason": "not_planned"}'
          elif [[ "${{ github.event.label.name }}" == "ğŸ‘Œ å®Œæˆ" ]]; then
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.SHEEP }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
              -d '{"state": "closed", "state_reason": "completed"}'
          fi

      - name: Handle closed issues
        if: github.event.action == 'closed'
        run: |
          existing_labels=$(curl -s -H "Authorization: token ${{ secrets.SHEEP }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} | jq -r '.labels | map(.name)')
          if [[ "${{ github.event.issue.state_reason }}" == "duplicate" ]]; then
            new_labels=$(echo $existing_labels | jq -c '. + ["âŒ é‡å¤"]' | sed 's/[][]//g' | sed 's/"//g')
            new_labels="[$new_labels]"
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.SHEEP }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
              -d '{"labels": '$new_labels'}'
          elif [[ "${{ github.event.issue.state_reason }}" == "completed" ]]; then
            new_labels=$(echo $existing_labels | jq -c '. + ["ğŸ‘Œ å®Œæˆ"]' | sed 's/[][]//g' | sed 's/"//g')
            new_labels="[$new_labels]"
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.SHEEP }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
              -d '{"labels": '$new_labels'}'
          fi
